sudo: required
dist: trusty
language: cpp
compiler: g++
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -y -qq
  - sudo apt-get install -y -qq gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
#  - sudo update-alternatives --install /usr/bin/g++  g++  /usr/bin/g++-4.8  90
#  - sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-4.8  90 
#  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 90
script: 
  - mkdir build
  - cd build
  - cmake .. 
  - make 
  - ./Test/BundleAgent_test
