#!/bin/sh
IFS=' '
DIR="$( cd "$( dirname "$0" )" && pwd )"
while read local_ref local_sha remote_ref remote_sha;
do
	echo "Passing UnitTests"
	SCRIPT=$(readlink -nf generateTestAndCoverage.sh)
	bash $SCRIPT
	RET=$?
	exit $RET
done
exit 0
