amd64_jessie:
	build: ./amd64_jessie
	command: sh -c 'cp build/*deb /pkg'
	volumes:
		- /pkg:/pkg
  working_dir: /aDTNPlus

arm6_jessie:
  build: ./arm6_jessie
  entrypoint: /usr/bin/qemu-arm-static
  command: sh -c 'cp build/*.deb /pkg'
  volumes:
    - /pkg:/pkg
    - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
  working_dir: /aDTNPlus

arm6_stretch:
  build: ./arm6_stretch
  entrypoint: /usr/bin/qemu-arm-static
  command: sh -c 'cp build/*.deb /pkg'
  volumes:
    - /pkg:/pkg
    - /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static
  working_dir: /aDTNPlus